/** Generated by dotenv-guard */
declare namespace NodeJS {
  export interface ProcessEnv {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    DATABASE_URL: string;
    TRANSFORMED_VAR: string;
    OPTIONAL_VAR?: string;
    BOOLEAN_FLAG: boolean;
  }

}
